version: "3"
services:
  mongodb:
    container_name: mongodb
    image : mongo
    ports:
        - 27018:27017
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
volumes:
  db-data:
  mongo-config: